# Generated by Django 5.2.4 on 2025-08-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default_event.jpg', null=True, upload_to='events/'),
        ),
    ]
